puppetlabs/puppetlabs-scheduled_task

.sync.yml
README.md
examples/create_task_v1.pp
examples/delete_task_v1.pp
lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_v1task.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/taskscheduler2_spec.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/taskscheduler2_v1task_spec.rb
spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb

This PR adds a new class and provider which has the same interface as the older V1
Scheduled Task.  This adapter class will implement the V1 methods but using the V2 API calls.
This PR also adds tests to ensure that the adapter behaves the same as the V1 puppet type
This PR also adds some basic integration tests, which may subsume the current acceptance tests

(MODULES-6264)(MODULES-6266) Create V2 API and V1 adapter

---

spec/acceptance/should_create_task_spec.rb
spec/acceptance/should_destroy_spec.rb

Previously in the acceptance tests the beaker method execute_manifest_on was
used however the test mode switcher gem does not support using this method in
agent only test mode.  This means we need to use the less explicit
execute_manifest method.  Fortunately our spec tests already only run on the
default node so there is no nett difference but it's still a little confusing
for new people.

(MODULES-6362) Change acceptance tests to execute_manifest

---

spec/acceptance/should_create_task_spec.rb
spec/acceptance/should_destroy_spec.rb

Windows Server 2016 core outputs a different error message from schtask.exe.
This caused the acceptance tests to file as the regex mathcers were too
specific.  This commit modifies the regex to be more leniant on the error
message checking.

(MODULES-6362) Update tests for Server 2016 Core

---

metadata.json

Currently the puppetforge has the 'Project URL' link which is pointing to the puppetlabs-iis module.  This fixes that :D.

Fix metadata which points to iis

---

lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet/provider/scheduled_task/win32_taskscheduler.rb
spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb

Previously if an invalid value for the day_of_week property was passed (e.g.
MON) it would fail with `Cannot convert "nil" to Fixnum`.  This commit adds
invalid value detection when building the bitmasked value and raises an error
which includes the bad value.  This commit also adds a test for this scenario.

(MODULES-6398) Fix error message on invalid day_of_week trigger

---

lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet/provider/scheduled_task/win32_taskscheduler.rb
spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb

Previously when changing from a monthly day of week to a monthly date trigger
type (and vice versa) Puppet would raise an error.  This was due to Puppet using
the same schedule name (monthly) for two distinct trigger types in windows API.
This commit adds an additional check to the tiggers_same? method which also
evaluates the underlying trigger type, not just the Puppet representation to
determine if two triggers are indeed the same.  This commit also adds tests for
this scenario.

(MODULES-6268) Fix error when switching monthly trigger types

---

README.md

Prior to this commit the documentation for the `scheduled_task` module
largely pointed back to the official Puppet documentation for information
on the type reference and on the usage of the resource. This commit
ensures that that information now lives in the scheduled_task module and
adds numerous clarifying examples of use.
This will allow future iterative work to continue in this module without
needing to point back to the not-actively-developed type and provider in
core Puppet. Documentation updates to the module can now be safely made.

(MODULES-6417) Add usage and examples to README

---

lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_v1task.rb
lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/taskscheduler2_spec.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/trigger_spec.rb

#14 should be merged first which restores existing type / provider to this module
- Report on the compatibility level of tasks enumerated from the
system.
This requires adding a value to the scheduled_task type named
compatibility. Based on how the provider works, it currently only
enumerates v1 tasks, and therefore only returns 1.
Since the property may now also be set in a manifest, limit the
value to 1 so that it cannot be set improperly. Default the value
to 1 to preserve backward compatibility.
`puppet resource` will now emit the value as well

(MODULES-6843) Refactor Trigger code from V1 -> V2 adapter class

---

README.md
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_task.rb
lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/taskscheduler2_task_spec.rb

These commits add a V2-only helper by cloning and updating the adapter. It adds integration tests for the new helper and strips away pieces of the helper which are for V1 tasks.
It is _out of scope_ to wire this helper up to the provider or otherwise alter the type/provider for this helper.

(MODULES-6844) Add v2-only helper

---

CHANGELOG.md
README.md
lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet/type/scheduled_task.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_task.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_v1task.rb
spec/unit/puppet/type/scheduled_task_spec.rb

- Report on the compatibility level of tasks enumerated from the
system.
This requires adding a value to the scheduled_task type named
compatibility. Based on how the provider works, it currently only
enumerates v1 tasks, and therefore only returns 1.
Since the property may now also be set in a manifest, limit the
value to 1 so that it cannot be set improperly. Default the value
to 1 to preserve backward compatibility.
`puppet resource` will now emit the value as well
A future commit will add compatibility versioning for V2 when
that helper is wired up.

(MODULES-6526) Add compatibility in task type

---

lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet/type/scheduled_task.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_task.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_v1task.rb
spec/unit/puppet/type/scheduled_task_spec.rb

Prior to this commit the code was added to enable
users to specify a compatibility version to create
a task. Unfortunately, there was no testing for
verifying idempotency. When run against an existing
task the resource would fail because it can not
handle the compatibility property.  This commit
ensures that the compatibility property is settable.

(MODULES-6526) Add setter for compatibility

---

lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_task.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_v1task.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/taskscheduler2_task_spec.rb
spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb

- Fix the complex require / `require_relative` setup that was causing
the Puppet autoloader to reload the `Trigger` class and redefine
previously defined constants
- Remove unnecessary Windows guard to make sure `Trigger` constants
are pulled in for specs on Linux. This also required removing
unnecessary declarations for `Puppet::Util::Windows::Error`
- Its no longer necessary to use Win32:: style constants given these
values are located in the various `Trigger::V1` nested clasess like
`Day`, `Month` and `Occurrence`.
- Remove the unnecessary `scheduler_trigger_types`, since the same
constants are already available inside
`PuppetX::PuppetLabs::ScheduledTask::Trigger::V2::Type::V1_TYPE_MAP`
- Replace the Win32 constants with appropriate substitutes available
in the `Day`, `Month`, `Flag` …

(MODULES-6895) Fix Trigger require / autoload reloading

---

lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet/type/scheduled_task.rb
spec/acceptance/should_create_task_spec.rb

Prior to this commit any calls to the win32 legacy provider after
the introduction of the compatibility setting cause a run to blow
up because that provider does not have a way to manage compatibility.
This commit adds a feature, `:compatibility`, and limits the methods
for compatibility setting and getting to that feature.  Note that this
method will cause the legacy provider and any provider that does not
support the feature to silently ignore compatibility if passed in a
manifest.  It will not error but it also won't do anything.
If swapping between providers, this can probably cause some strange
behavior.  All net-new features and properties for this module will
probably need to be added this way to prevent explosions in the
legacy provider.
The added acceptance test is a simple …

(MODULES-6526) Confine compatibility to a feature

---

lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_task.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2_v1task.rb
lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/taskscheduler2_task_spec.rb
spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb
spec/unit/puppet_x/puppetlabs/scheduled_task/trigger_spec.rb

This should be merged prior to #27, partly because some code is being extracted from `taskscheduler_api2` and that code is about to be copied into `win32_taskscheduler`.  Therefore it makes more sense to do this work first, especially given it fixes some critical bugs in converting `ITrigger` back to a V1 internal representation.

(MODULES-6895) Additional Trigger conversion bugfixes and refactorings

---

lib/puppet/type/scheduled_task.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/v1adapter_spec.rb

Prior to this commit the taskscheduler2 helper required the puppet
win32 code from core puppet; there are no longer any constants or
other calls reliant on this code so we remove it.

(MODULES-6868) Remove unnecessary library include

---

spec/spec_helper_acceptance.rb

- With master / agent setups that are being used in conjunction with
testmode_switcher, all nodes should receive copies of a given module.
There is no reason to restrict host types.
Further, use the Beaker helper designed for installing modules.

(maint) Ensure module copied to all hosts

---

lib/puppet_x/puppetlabs/scheduled_task/v1adapter.rb
spec/acceptance/should_create_task_spec.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/v1adapter_spec.rb

Builds on #38 which should be merged first
- Commit 77d2d4b introduced the setting of compatibility on the
win32_taskscheduler provider.
However, since it set `compatibility =`, the actual setter method
for the class instance was never properly called, which would
result in improper compatibility level being set.
This may vary by host, but on Windows 2008R2, this defaulted to
creating new tasks with a compatibility level of 2, instead of the
desired 1.
- Running a simple manifest like the following, would result in
Puppet creating a new task with the wrong compatiblity level. Since
the provider filters on a compatibility level of 1 or lower,
subsequent runs would never see the existing task, and would think
it necessary to create the task. In addition to setting the wrong
compat level, it …

(MODULES-6526) Fix win32_taskscheduler compatibility

---

lib/puppet_x/puppetlabs/scheduled_task/v1adapter.rb
lib/puppet_x/puppetlabs/scheduled_task/v2adapter.rb

- There was confusing (especially with respect to scoping rules) code
in adapters for getting / setting flag values.
Remove the unneeded code in getter.
Change variable names in setter to not be the same as the method

(maint) Simplify flag getter/setter in adapters

---

lib/puppet_x/puppetlabs/scheduled_task/error.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2.rb

- There are a number of COM HRESULT values specific to the task
scheduler APIs.  Namespace all of those values in the module
PuppetX::PuppetLabs::ScheduledTask::TaskScheduler2::Error
Add a helper function that can convert values to their 2s
complement, which is somehow how APIs may return them.
For instance, for values about 0x800XXXXX, it's common to see both
usages in the wild.  For instance, ERROR_FILE_NOT_FOUND can either
be 0x80070002 or -2147024894.
Typically the WIN32OLERuntimeError class will contain messages
that are using the 80070002 style format.
- Rework code that catches WIN32OLERuntimeError, adding a helper
method to match on the embedded string values for a given HRESULT
in both formats.

(maint) Add all COM error constants from winerror.h

---

lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2.rb
lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
lib/puppet_x/puppetlabs/scheduled_task/v1adapter.rb
lib/puppet_x/puppetlabs/scheduled_task/v2adapter.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/taskscheduler2_spec.rb

Instead of having all constants remain under the `TaskScheduler2` namespace, prefix each set of constants with their appropriate type. Also:
* Adds missing constants
* Adds missing types of constants
* Updates MSDN links to point to newer docs
* Removes the mostly unused V1 flag constants

(maint) Reorganize / add all constants from taskschd.h

---

spec/integration/puppet_x/puppetlabs/scheduled_task/v1adapter_spec.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/v2adapter_spec.rb
spec/unit/puppet_x/puppetlabs/scheduled_task/trigger_spec.rb

- Ruby is generating constant redefinition warnings. This could lead
to problems in the future, so correct it now by changing the scope.

(maint) Remove global V2 constants from tests

---

lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet/provider/scheduled_task/win32_taskscheduler.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2.rb
lib/puppet_x/puppetlabs/scheduled_task/v1adapter.rb
lib/puppet_x/puppetlabs/scheduled_task/v2adapter.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/v1adapter_spec.rb
spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb

- Flags inside of scheduled tasks are a V1 construct. Without any V1
API usage inside this module, this is replaced with an
implementation that covers the only setting currently
implemented - "Enabled".
- Enabled flag is provided directly from the ITaskDefinition
property Setting, which is an ITaskSettings interface pointer.
- Flags only sticks around when testing against the old version of
the code that was previously shipped in Puppet and implemented
inside of Win32::TaskScheduler.

(MODULES-7420) Remove flags

---

spec/integration/puppet_x/puppetlabs/scheduled_task/v1adapter_spec.rb
spec/legacy_taskscheduler.rb
spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb

Prior to this commit the spec tests relied on the built-in
utility code for the windows task scheduler inside of core
puppet. With the Puppet 6 release this code will be removed,
meaning the tests relying on this reference will fail.
This commit copies that code into a helper file in the spec
folder and ensures the tests relatively require it instead
of pointing to the utility baked into Puppet.
This should ensure the tests continue to pass and backwards
compatibility can be safely maintained once Puppet 6 is
released.

(MAINT) Add legacy taskscheduler code as helper and freeze

---

lib/puppet_x/puppetlabs/scheduled_task/error.rb
lib/puppet_x/puppetlabs/scheduled_task/taskscheduler2.rb
lib/puppet_x/puppetlabs/scheduled_task/v1adapter.rb
lib/puppet_x/puppetlabs/scheduled_task/v2adapter.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/taskscheduler2_spec.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/v1adapter_spec.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/v2adapter_spec.rb

~~Builds on #51, which should be merged first~~
Removes a number of code paths from `TaskScheduler2` that were unnecessary and/or unnecessarily complex. Many of these methods took a `definition` object and only performed a single action with it, and could easily be inlined into the two adapter classes.
This is the first part of a class restructuring that will:
* Merge the 2 adapter classes into a single base implementation (since they share 99% of their impl)
* Potentially refactor remaining methods from `TaskScheduler2` directly into the base adapter class (there's only about 120 lines of actual code in `TaskScheduler2` module now - and it would probably be fine)
* Ultimately this should simplify the class hierarchy so that maintenance is simpler

(MODULES-7425) Remove unnecessary TaskScheduler2 methods

---

.pdkignore
.pmtignore

- The PDK looks at .pdkignore to determine what to include / exclude
with the built tarball - see
puppetlabs/pdk:lib/pdk/module/build.rb@c6db211#L176-L182
- PMT (Puppet module tool) looks at .pmtignore for the same thing,
which is how a module is typically bundled in CI or through a
local workflow with `bundle exec rake build`

(MODULES-7651) Remove spec folder from builds

---

lib/puppet_x/puppetlabs/scheduled_task/task.rb
spec/acceptance/should_create_task_spec.rb
spec/spec_helper_acceptance.rb

Prior to this change, if a manifest specified a user and a password to
run a task, those settings were not respected. Puppet's commandline
logging would first claim that a task was create, but then throw an OLE
error.
This change ensures that a username and password can successfully be
specified for a task.

(MODULES-7240) Setting User For A Task Fails

---

spec/acceptance/should_create_task_spec.rb

The change at 30f2f5b71e3c4cefbb87ec4c1154ceca560e3f7f introduced calls
to the string method `match?`. This method did not exist prior to
ruby 2.4. This change uses an alternative syntax that will work with
older versions of ruby.

(MAINT) Spec Fails On Old Ruby

---

lib/puppet_x/puppetlabs/scheduled_task/task.rb

- Currently, a new Service instance is created each time:
* The task method is called to load a task, which is in turn
called by the initializer for Task
* For each depth of the folder hierarchy for enum_task_names,
which is called when retrieving all tasks
* When a task is deleted
* When a task is saved
- This generates a lot of unnecessary object creation overhead and
can be minimized by memoizing the first created instance

(maint) Memoize the Schedule.Service COM instance

---

lib/puppet_x/puppetlabs/scheduled_task/task.rb

The giant diffs from `pdk update` are line endings differences.

MODULES-8695

---

CHANGELOG.md
README.md
lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet/provider/scheduled_task/win32_taskscheduler.rb
lib/puppet/type/scheduled_task.rb
lib/puppet_x/puppetlabs/scheduled_task/task.rb
spec/integration/puppet_x/puppetlabs/scheduled_task/task_spec.rb
spec/unit/puppet/provider/scheduled_task/win32_taskscheduler_spec.rb

Prior to this commit the type and providers did not support specifying subfolders in which
to place a scheduled task. This commit adds support to the type and the taskscheduler_api2
provider for specifying scheduled tasks in subfolders.
This feature only exists for tasks whose compatibility is 2 or higher which prevents it from
being used on the legacy win32_taskscheduler provider altogether and necessitates some
validation prior to runtime.
This commit adds such validation by failing with descriptive errors during resource validation.
This new functionality requires the ability to scaffold folders in which to place the scheduled
task, which now happens automatically and only if the folder path does not already exist.
This commit does NOT add functionality for pruning the folders on task …

(MODULES-7203) Support nonroot task folders

---

.rubocop.yml
.sync.yml
Gemfile
Rakefile
appveyor.yml
metadata.json
spec/spec_helper.rb

Previously the module unmanaged the Appveyor CI file when converted to Litmus.
This commit allows the Appveyor CI file to be managed.

(PDK-1501) Allow Appveyor CI config to be templated

---

.sync.yml
appveyor.yml
metadata.json

See full description [here](https://confluence.puppetlabs.com/display/ECO/Inability+to+run+puppetlabs-scheduled_task+in+rspec_parallel+mode). To summarise:
- `parallel_spec` was enabled as part of this PR: https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/104
- This caused AppVeyor CI tests failures
- It was discovered that the tests within [task_spec.rb](https://github.com/puppetlabs/puppetlabs-scheduled_task/blob/e5fc25063716e857dd2dc4d169d1de85a9adb2a8/spec/integration/puppet_x/puppetlabs/scheduled_task/task_spec.rb) are not thread safe
- Tests are modifying the scheduled task configuration via the Puppet Agent, whilst the [results are being read back from PowerShell](https://github.com/puppetlabs/puppetlabs-scheduled_task/blob/e5fc25063716e857dd2dc4d169d1de85a9adb2a8/spec/in …

(MODULES-10241) Revert AppVeyor test exec to serial mode

---

spec/acceptance/should_destroy_spec.rb

Encountering errors on AppVeyor as the error message being returned for [this negative test](https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/116/files#diff-a5b71a8a826396d01399d7e2c62fa515R40) is:
```
ERROR: The system cannot find the path specified.
```
whereas the test is expecting the error:
```
ERROR: The system cannot find the file specified.
```
Still need investigation as to why there is a difference in the error message ("file" vs "path"). Unable to reproduce with Windows images provisioned locally (tried on Server 2008 R2 and Server 2016). There may be something unique to AppVeyor's particular images.

(maint) Update spec test error message expectations

---

lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
spec/acceptance/should_create_task_spec.rb

We were not correctly determining the idempotency of a scheduled task that had a [MonthlyDOWTrigger](https://docs.microsoft.com/en-gb/windows/win32/taskschd/monthlydowtrigger) set to `last`:
```
'which_occurrence' => 'last'
```
The task was being correctly set on the Windows Server instances, but when we read back the task, we were determining that the `Task.Definition.Triggers[i].WeeksOfMonth` attribute was `0` (i.e. nothing defined). Instead, we should be checking the [RunOnLastWeekOfMonth](https://docs.microsoft.com/en-gb/windows/win32/taskschd/monthlydowtrigger-runonlastweekofmonth) to determine if the task is set to run on the last week of the month.
**NOTE:** We are not changing how this parameter is configured, just how it is read back.

(MODULES-10101) Use RunOnLastWeekOfMonth for which_occurrence = last

---

lib/puppet_x/puppetlabs/scheduled_task/trigger.rb

In https://github.com/puppetlabs/puppetlabs-scheduled_task/pull/145 it
looks as though we removed the empty check on `datetime_string`.
This was causing the PE Patch Management tasks to fail in PE 2019.8.1.

(MODULES-10783) Add back empty? check for `datetime_string` value

---

README.md
lib/puppet/type/scheduled_task.rb
lib/puppet_x/puppetlabs/scheduled_task/trigger.rb
spec/acceptance/should_create_task_spec.rb
spec/unit/puppet_x/puppetlabs/scheduled_task/trigger_spec.rb

Prior to this change, attempting to create a trigger that will run on
the last day of each selected month will fail. The error claims that a
a value is out of range
```
OLE error code:0 in <Unknown>
<No Description>
HRESULT error code:0x8002000a
Out of present range.
```
Microsoft [documentation] claims in one place that the correct way to
specify the last day of a month is to effectively translate a bitmask
value of day 32 and pass that into the `{get:set}_DaysOfMonth` method
on the trigger object. The module was previously coded to do exactly
this. The provider and it's helpers would catch the string value 'last'
in the `on` property of a `monthly` trigger and translate it into the
bit mask. This is what resulted in the error, because it turns out that
the position for day 32 in the bit …

(MODULES-10893) Fix Last Day Of Month Trigger

---

REFERENCE.md
lib/puppet/type/scheduled_task.rb
lib/puppet_x/puppetlabs/scheduled_task/task.rb

Since the enhancement intended to help sysadmins, pulled in as #150: When not setting a password, this is interpreted as "Run only when user is logged on".
When configuring a scheduled task to use a Group Managed Service Account (gMSA) principal, there is no password to provide. The scheduler will get the password automatically when properly configured, and should be able to run the task even though the service account is not "logged on". Otherwise, the Managed Service Account is never "logged on" so the task does not run on expected schedule.
It does not seem viable to add a proper test case for this particular situation without an AD domain configuration and a proper gMSA in place. Without a correct gMSA, an error message stating "No mapping between account names and security IDs was …

(MODULES-10986) Fix gMSA username support

---

metadata.json

Prior to this commit the metadata.json file for this module listed OSs that are not supported by puppet agent as supported. This commit aims to refactor the metadata.json file to only list OSs that are supported by puppet agent.
In this commit:
- Support for Windows Server 2008 and 2008 R2 was removed. 
- Support for Windows 7, 8 and 8.1 was removed.
﻿
The list of supported OSs can be found here:
https://puppet.com/docs/pe/2021.7/supported_operating_systems.html

(MAINT) Dropped support for Windows(7,8,8.1, 2008 Server and 2008 R2 Server)

---

.devcontainer/devcontainer.json
.github/workflows/auto_release.yml
.github/workflows/nightly.yml
.github/workflows/pr_test.yml
.github/workflows/release.yml
.github/workflows/spec.yml
Gemfile
REFERENCE.md
metadata.json

Prior to this commit, upon attempting to run the autorelease github action, the module run into an error due to outdated PDK package.
This commit aims to update all the gems, workflows and .json files with the latest pdk update.

(MAINT) PDK update

---

.rubocop_todo.yml
spec/acceptance/should_create_task_spec.rb
spec/unit/puppet_x/puppetlabs/scheduled_task/trigger_spec.rb

Fixing CI failure due to rubocop
```
Split RSpec/FilePath into RSpec/SpecFilePathSuffix and RSpec/SpecFilePathFormat. RSpec/FilePath cop is enabled by default, the two new cops are pending and need to be enabled explicitly. (@ydah)
Add RSpec/MetadataStyle and RSpec/EmptyMetadata cops.
```
Mention any related issues or pull requests.

[CAT-1382] : Fixing CI failure due to rubocop

---

README.md
lib/puppet/provider/scheduled_task/taskscheduler_api2.rb
lib/puppet/type/scheduled_task.rb
lib/puppet_x/puppet_labs/scheduled_task/task.rb
lib/puppet_x/puppet_labs/scheduled_task/trigger.rb
spec/unit/puppet_x/puppet_labs/scheduled_task/trigger_spec.rb

This PR adds delay properties to scheduled task triggers. This feature is currently missing from the module, but adding delays to triggers is a useful function, supported from compatibility version 2 onwards.
- The logic is aware of schedule-based vs event-based triggers, and adds the required delay property for each style
- Warnings are logged if the delay is added to a trigger that doesn't support it or if the compatibility mode is below 2 (which doesn't support trigger delays)
- The format of the delay input is [ISO 8601](https://www.w3.org/TR/xmlschema-2/#duration), as per the [MS implementation](https://learn.microsoft.com/en-us/windows/win32/taskschd/taskschedulerschema-delay-boottriggertype-element)
- Debug messages have been added to provide detailed trigger information
Example of …

Add delay properties to triggers
